var annotated_dup =
[
    [ "std", "namespacestd.html", [
      [ "hash< stdui::component_id >", "structstd_1_1hash_3_01stdui_1_1component__id_01_4.html", "structstd_1_1hash_3_01stdui_1_1component__id_01_4" ]
    ] ],
    [ "stdui", "namespacestdui.html", [
      [ "detail", "namespacestdui_1_1detail.html", [
        [ "stack_traits", "structstdui_1_1detail_1_1stack__traits.html", null ],
        [ "stack_traits< stack_axis::horizontal >", "structstdui_1_1detail_1_1stack__traits_3_01stack__axis_1_1horizontal_01_4.html", "structstdui_1_1detail_1_1stack__traits_3_01stack__axis_1_1horizontal_01_4" ],
        [ "stack_traits< stack_axis::vertical >", "structstdui_1_1detail_1_1stack__traits_3_01stack__axis_1_1vertical_01_4.html", "structstdui_1_1detail_1_1stack__traits_3_01stack__axis_1_1vertical_01_4" ]
      ] ],
      [ "app_config", "structstdui_1_1app__config.html", "structstdui_1_1app__config" ],
      [ "application", "classstdui_1_1application.html", "classstdui_1_1application" ],
      [ "arranged_layout", "structstdui_1_1arranged__layout.html", "structstdui_1_1arranged__layout" ],
      [ "cached_text_measurer", "classstdui_1_1cached__text__measurer.html", "classstdui_1_1cached__text__measurer" ],
      [ "color", "structstdui_1_1color.html", "structstdui_1_1color" ],
      [ "component_base", "classstdui_1_1component__base.html", "classstdui_1_1component__base" ],
      [ "component_context", "classstdui_1_1component__context.html", "classstdui_1_1component__context" ],
      [ "component_evaluator", "classstdui_1_1component__evaluator.html", "classstdui_1_1component__evaluator" ],
      [ "component_expression", "structstdui_1_1component__expression.html", "structstdui_1_1component__expression" ],
      [ "component_id", "structstdui_1_1component__id.html", "structstdui_1_1component__id" ],
      [ "component_registry", "classstdui_1_1component__registry.html", "classstdui_1_1component__registry" ],
      [ "dynamic_list_expression", "structstdui_1_1dynamic__list__expression.html", "structstdui_1_1dynamic__list__expression" ],
      [ "edge_insets", "structstdui_1_1edge__insets.html", "structstdui_1_1edge__insets" ],
      [ "evaluation_context", "structstdui_1_1evaluation__context.html", "structstdui_1_1evaluation__context" ],
      [ "event_dispatcher", "classstdui_1_1event__dispatcher.html", "classstdui_1_1event__dispatcher" ],
      [ "flex_policy", "structstdui_1_1flex__policy.html", "structstdui_1_1flex__policy" ],
      [ "font_descriptor", "structstdui_1_1font__descriptor.html", "structstdui_1_1font__descriptor" ],
      [ "grid_expression", "structstdui_1_1grid__expression.html", "structstdui_1_1grid__expression" ],
      [ "grid_options", "structstdui_1_1grid__options.html", "structstdui_1_1grid__options" ],
      [ "hstack_expression", "structstdui_1_1hstack__expression.html", "structstdui_1_1hstack__expression" ],
      [ "id_storage", "structstdui_1_1id__storage.html", "structstdui_1_1id__storage" ],
      [ "id_storage< std::string_view >", "structstdui_1_1id__storage_3_01std_1_1string__view_01_4.html", "structstdui_1_1id__storage_3_01std_1_1string__view_01_4" ],
      [ "identified_expression", "structstdui_1_1identified__expression.html", "structstdui_1_1identified__expression" ],
      [ "inspection_node", "structstdui_1_1inspection__node.html", "structstdui_1_1inspection__node" ],
      [ "keyboard_event", "structstdui_1_1keyboard__event.html", "structstdui_1_1keyboard__event" ],
      [ "keyboard_modifiers", "structstdui_1_1keyboard__modifiers.html", "structstdui_1_1keyboard__modifiers" ],
      [ "layout_box", "structstdui_1_1layout__box.html", "structstdui_1_1layout__box" ],
      [ "layout_node", "structstdui_1_1layout__node.html", "structstdui_1_1layout__node" ],
      [ "layout_result", "structstdui_1_1layout__result.html", "structstdui_1_1layout__result" ],
      [ "mouse_event", "structstdui_1_1mouse__event.html", "structstdui_1_1mouse__event" ],
      [ "null_platform", "classstdui_1_1null__platform.html", "classstdui_1_1null__platform" ],
      [ "null_renderer", "classstdui_1_1null__renderer.html", "classstdui_1_1null__renderer" ],
      [ "null_window", "classstdui_1_1null__window.html", "classstdui_1_1null__window" ],
      [ "overlay_expression", "structstdui_1_1overlay__expression.html", "structstdui_1_1overlay__expression" ],
      [ "overlay_options", "structstdui_1_1overlay__options.html", "structstdui_1_1overlay__options" ],
      [ "platform", "classstdui_1_1platform.html", "classstdui_1_1platform" ],
      [ "platform_window", "classstdui_1_1platform__window.html", "classstdui_1_1platform__window" ],
      [ "point", "structstdui_1_1point.html", "structstdui_1_1point" ],
      [ "proposal", "structstdui_1_1proposal.html", "structstdui_1_1proposal" ],
      [ "rect", "structstdui_1_1rect.html", "structstdui_1_1rect" ],
      [ "renderer", "classstdui_1_1renderer.html", "classstdui_1_1renderer" ],
      [ "renderer_factory", "classstdui_1_1renderer__factory.html", "classstdui_1_1renderer__factory" ],
      [ "resize_event", "structstdui_1_1resize__event.html", "structstdui_1_1resize__event" ],
      [ "runtime", "classstdui_1_1runtime.html", "classstdui_1_1runtime" ],
      [ "simple_event_dispatcher", "classstdui_1_1simple__event__dispatcher.html", "classstdui_1_1simple__event__dispatcher" ],
      [ "size", "structstdui_1_1size.html", "structstdui_1_1size" ],
      [ "size_constraint", "structstdui_1_1size__constraint.html", "structstdui_1_1size__constraint" ],
      [ "stack_options", "structstdui_1_1stack__options.html", "structstdui_1_1stack__options" ],
      [ "state", "classstdui_1_1state.html", "classstdui_1_1state" ],
      [ "state_handle", "classstdui_1_1state__handle.html", "classstdui_1_1state__handle" ],
      [ "state_key", "structstdui_1_1state__key.html", "structstdui_1_1state__key" ],
      [ "state_key_hash", "structstdui_1_1state__key__hash.html", "structstdui_1_1state__key__hash" ],
      [ "state_storage", "classstdui_1_1state__storage.html", "classstdui_1_1state__storage" ],
      [ "stroke_style", "structstdui_1_1stroke__style.html", "structstdui_1_1stroke__style" ],
      [ "text_expression", "structstdui_1_1text__expression.html", "structstdui_1_1text__expression" ],
      [ "text_measurer", "classstdui_1_1text__measurer.html", "classstdui_1_1text__measurer" ],
      [ "text_measurer_factory", "classstdui_1_1text__measurer__factory.html", "classstdui_1_1text__measurer__factory" ],
      [ "typed_component", "classstdui_1_1typed__component.html", "classstdui_1_1typed__component" ],
      [ "vstack_expression", "structstdui_1_1vstack__expression.html", "structstdui_1_1vstack__expression" ]
    ] ]
];